config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:ranking_id, :rating, :company_id, :image, :weekdays_start, :time, :weekdays_end, :holidays_start, :holidays_end, :size_m, :integer, :size_l, :walk_time, :length, :power, :wifi)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sercaffe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ranking_id %>
    <%= form.number_field :ranking_id %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.number_field :company_id %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :weekdays_start %>
    <%= form.text_field :weekdays_start %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time %>
  </div>

  <div class="field">
    <%= form.label :weekdays_end %>
    <%= form.time_select :weekdays_end %>
  </div>

  <div class="field">
    <%= form.label :holidays_start %>
    <%= form.time_select :holidays_start %>
  </div>

  <div class="field">
    <%= form.label :holidays_end %>
    <%= form.time_select :holidays_end %>
  </div>

  <div class="field">
    <%= form.label :size_m %>
    <%= form.text_field :size_m %>
  </div>

  <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer %>
  </div>

  <div class="field">
    <%= form.label :size_l %>
    <%= form.number_field :size_l %>
  </div>

  <div class="field">
    <%= form.label :walk_time %>
    <%= form.number_field :walk_time %>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.number_field :length %>
  </div>

  <div class="field">
    <%= form.label :power %>
    <%= form.number_field :power %>
  </div>

  <div class="field">
    <%= form.label :wifi %>
    <%= form.text_field :wifi %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Ranking</th>
      <th>Rating</th>
      <th>Company</th>
      <th>Image</th>
      <th>Weekdays start</th>
      <th>Time</th>
      <th>Weekdays end</th>
      <th>Holidays start</th>
      <th>Holidays end</th>
      <th>Size m</th>
      <th>Integer</th>
      <th>Size l</th>
      <th>Walk time</th>
      <th>Length</th>
      <th>Power</th>
      <th>Wifi</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.ranking_id %></td>
        <td><%= store.rating %></td>
        <td><%= store.company_id %></td>
        <td><%= store.image %></td>
        <td><%= store.weekdays_start %></td>
        <td><%= store.time %></td>
        <td><%= store.weekdays_end %></td>
        <td><%= store.holidays_start %></td>
        <td><%= store.holidays_end %></td>
        <td><%= store.size_m %></td>
        <td><%= store.integer %></td>
        <td><%= store.size_l %></td>
        <td><%= store.walk_time %></td>
        <td><%= store.length %></td>
        <td><%= store.power %></td>
        <td><%= store.wifi %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ranking:</strong>
  <%= @store.ranking_id %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @store.rating %>
</p>

<p>
  <strong>Company:</strong>
  <%= @store.company_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @store.image %>
</p>

<p>
  <strong>Weekdays start:</strong>
  <%= @store.weekdays_start %>
</p>

<p>
  <strong>Time:</strong>
  <%= @store.time %>
</p>

<p>
  <strong>Weekdays end:</strong>
  <%= @store.weekdays_end %>
</p>

<p>
  <strong>Holidays start:</strong>
  <%= @store.holidays_start %>
</p>

<p>
  <strong>Holidays end:</strong>
  <%= @store.holidays_end %>
</p>

<p>
  <strong>Size m:</strong>
  <%= @store.size_m %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @store.integer %>
</p>

<p>
  <strong>Size l:</strong>
  <%= @store.size_l %>
</p>

<p>
  <strong>Walk time:</strong>
  <%= @store.walk_time %>
</p>

<p>
  <strong>Length:</strong>
  <%= @store.length %>
</p>

<p>
  <strong>Power:</strong>
  <%= @store.power %>
</p>

<p>
  <strong>Wifi:</strong>
  <%= @store.wifi %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>